services:
  frontend:
    build:
      context: ./poc-submodule-frontend
      dockerfile: Dockerfile
    volumes:
      - ./poc-submodule-frontend/app:/workspace/app
    ports:
      - 3000:5173
  backend:
    build:
      context: ./poc-submodule-backend
      dockerfile: Dockerfile
    ports:
      - 3001:3001